// Generated by https://quicktype.io

declare interface WPFaculty {
  id: number
  date: string
  date_gmt: string
  guid: GUID
  modified: string
  modified_gmt: string
  slug: string
  status: Status
  type: Type
  link: string
  title: GUID
  featured_media: number
  template: string
  acf: AcfFaculty
  _links: Links
}

declare interface Links {
  self: About[]
  collection: About[]
  about: About[]
  'wp:attachment': About[]
  curies: Cury[]
  'wp:featuredmedia'?: WpFeaturedmedia[]
}

declare interface About {
  href: string
}

declare interface Cury {
  name: Name
  href: Href
  templated: boolean
}

declare enum Href {
  HTTPSAPIWOrgRel = 'https://api.w.org/{rel}'
}

declare enum Name {
  Wp = 'wp'
}

declare interface WpFeaturedmedia {
  embeddable: boolean
  href: string
}

declare interface AcfFaculty {
  first_name: string
  last_name: string
  title: string
  bio: string
  phone: string
  email: string
  website: string
  mailing_address: MailingAddress
  directory_category: Type[]
}

declare enum Type {
  Staff = 'staff'
}

declare enum MailingAddress {
  Gettysburg = 'Gettysburg',
  Philadelphia = 'Philadelphia'
}

declare interface GUID {
  rendered: string
}

declare enum Status {
  Publish = 'publish'
}
