// Generated by https://quicktype.io

declare interface WPPost {
  id: number
  date: string
  date_gmt: string
  guid: GUID
  modified: string
  modified_gmt: string
  slug: string
  status: string
  type: string
  link: string
  title: GUID
  content: Content
  excerpt: Content
  author: number
  featured_media: number
  comment_status: string
  ping_status: string
  sticky: boolean
  template: string
  format: string
  meta: any[]
  categories: number[]
  tags: any[]
  acf: AcfPost
  _links: Links
}

declare interface Links {
  self: About[]
  collection: About[]
  about: About[]
  author: Author[]
  replies: Author[]
  'version-history': VersionHistory[]
  'predecessor-version': PredecessorVersion[]
  'wp:attachment': About[]
  'wp:term': WpTerm[]
  curies: Cury[]
}

declare interface About {
  href: string
}

declare interface Author {
  embeddable: boolean
  href: string
}

declare interface Cury {
  name: string
  href: string
  templated: boolean
}

declare interface PredecessorVersion {
  id: number
  href: string
}

declare interface VersionHistory {
  count: number
  href: string
}

declare interface WpTerm {
  taxonomy: string
  embeddable: boolean
  href: string
}

declare interface AcfPost {
  thumbnail_image: ThumbnailImage | false
  image: string | false
}

declare interface ThumbnailImage {
  ID: number
  id: number
  title: string
  filename: string
  filesize: number
  url: string
  link: string
  alt: string
  author: string
  description: string
  caption: string
  name: string
  status: string
  uploaded_to: number
  date: string
  modified: string
  menu_order: number
  mime_type: string
  type: string
  subtype: string
  icon: string
  width: number
  height: number
  sizes: Sizes
}

declare interface Sizes {
  thumbnail: string
  'thumbnail-width': number
  'thumbnail-height': number
  medium: string
  'medium-width': number
  'medium-height': number
  medium_large: string
  'medium_large-width': number
  'medium_large-height': number
  large: string
  'large-width': number
  'large-height': number
  'post-thumbnail': string
  'post-thumbnail-width': number
  'post-thumbnail-height': number
}

declare interface Content {
  rendered: string
  protected: boolean
}

declare interface GUID {
  rendered: string
}
